---
- name: Mount NFS share on Agent
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install NFS client package
      yum:
        name: nfs-utils
        state: present

    - name: Create mount folder
      file:
        path: /mnt/nfs_client
        state: directory

    - name: Mount NFS share
      mount:
        path: /mnt/nfs_client
        src: 172.31.78.27:/mnt/nfs_share
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Add entry to fstab for auto mount
      mount:
        path: /mnt/nfs_client
        src: 172.31.78.27:/mnt/nfs_share
        fstype: nfs
        opts: defaults
        state: present
